### ISSUE TITLE
Mosaic of Sentinel2 images

### ISSUE THREAD

**Issue by igeofr** [remicres/otb-mosaic#12]
Hi,
I’m trying to use otbcli_mosaic (OTB 6.6.1 for MacOS) in order to generate an mosaic of Sentinel2 images. The problem is that the result is not as expected, especially when the same tile is composed of two images.

Code :
`OTB_MAX_RAM_HINT=6144 GDAL_CACHEMAX=10240 otbcli_Mosaic -il /img1b1.tif /img2b1.tif -vdcut /img1b1.shp /img2b1.shp -harmo.method band -out /Mosaic.tif float -ram 6144`

This is the result that I’m getting:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/7761073/58108516-83c08f80-7bdb-11e9-88cc-270629f0aaa8.png">

Do you have a solution for me?

Edit : The mosaic only works if :
`-harmo.method none`

Thanks.
Regards,

**Comment by remicres** [comment]
Your preview shows a lot of images (more than 2). Can you show the output image of the following command?
`otbcli_Mosaic -il img1b1.tif img2b1.tif  -out Mosaic.tif`

Please also note that radiometric/color harmonization only works on valid (i.e. different than do-data value), overlapping pixels of input images: if images do not overlap, the harmonization wont't work. If you want to mosaic several scenes, with some non-overlapping scenes that have the same radiometry, you can first mosaic these scenes together with`harmo.method none` then mosaic these resulting mosaics using `harmo.method band`

**Comment by igeofr** [comment]
Thank you for your feedback.
Here is the corresponding output image - `otbcli_Mosaic -il img1b1.tif img2b1.tif -out Mosaic.tif` :
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/7761073/58631924-8a35c200-82d3-11e9-9807-59a1ed822f6a.png">

**Comment by igeofr** [comment]
If I test with the first two lines of images :
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/7761073/58634890-f61c2880-82db-11e9-8a9c-ec337788293d.png">

**harmo.method band**
1. `otbcli_Mosaic -il img1b1.tif img2b1.tif -out Mosaic.tif -harmo.method band -harmo.cost rmse`
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/7761073/58637710-a3923a80-82e2-11e9-985c-b0b177ff1fda.png">

2. `otbcli_Mosaic -il img1b1.tif img2b1.tif -vdcut img1b1.shp img2b1.shp -out Mosaic.tif -harmo.method band -harmo.cost rmse`
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/7761073/58637752-c3296300-82e2-11e9-9b5c-6d803ebcde31.png">

**harmo.method none**

3. `otbcli_Mosaic -il img1b1.tif img2b1.tif -vdcut img1b1.shp img2b1.shp -out Mosaic.tif -harmo.method none`
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/7761073/58637626-6ded5180-82e2-11e9-86a7-35c1b9e62e40.png">

4. `otbcli_Mosaic -il img1b1.tif img2b1.tif -out Mosaic.tif -harmo.method none`
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/7761073/58638193-c3762e00-82e3-11e9-9cbb-6b5b4a14413a.png">

**Comment by remicres** [comment]
I think that the problem comes from the nodata (i.e. Background) value: the app does not seem to use it, and the result looks good only when you use vector data....

In Mosaic, default nodata value is 0. Can you check that the background values in your images are 0? (In incoming version of Mosaic, you will be able to use another value than 0).

**Comment by igeofr** [comment]
I confirm the problem came from the no-data values. I restarted all the steps with no-data at 0 and it works.

![image](https://user-images.githubusercontent.com/7761073/58716969-b0ce2880-83b9-11e9-8215-cf505ac2a53c.png)

Thank you.
