### ISSUE TITLE
build failures on msvc2015

### ISSUE THREAD

**Issue by rkanavath** [remicres/otb-mosaic#3]
here is a first build of otb-mosaic with msvc2015

otb is using develop branch 
http://dash.orfeo-toolbox.org/viewBuildError.php?buildid=246023

**Comment by remicres** [comment]
The develop branch mosaic-msvc2015 is not currently on dashboard

**Comment by rkanavath** [comment]
i killed the scheduler job yesterday and today at noon. due to number of feature branches remote modules didn't make it to list. This will be fixed today.

**Comment by rkanavath** [comment]
once you find remote module in stable, don't forgot to update the git_tag in Modules/Remote/Mosaic.remote.

dashboard will pick up only from the tag mentioned in GIT_TAG rather than master

**Comment by rkanavath** [comment]
new build
https://dash.orfeo-toolbox.org/viewBuildError.php?buildid=247288

**Comment by rkanavath** [comment]
i update git tag to last commit and here is the build
https://dash.orfeo-toolbox.org/viewBuildError.php?buildid=247367

**Comment by remicres** [comment]
This might be fixed. Should I update the GIT TAG in the develop branch?

**Comment by rkanavath** [comment]
yes please.

**Comment by rkanavath** [comment]
still failing..
https://dash.orfeo-toolbox.org/buildSummary.php?buildid=247600

**Comment by remicres** [comment]
The error related to the QuadraticallyConstrainedSolver should be fixed now. I've updated the tag of the mosaic on develop branch... Let's see tomorrow

**Comment by remicres** [comment]
There are 2 failing test on msvc. Strange. I'll be able to look into it in few days

**Comment by rkanavath** [comment]
thanks. build is passing. but two tests are failing on windows

https://dash.orfeo-toolbox.org/viewTest.php?onlyfailed&buildid=248203

any idea?

**Comment by remicres** [comment]
It might come from the Danielson distance map image filter from ITK, but I am doubtful.
I have to look closer and install msvc on windows environment.
On dashboard, is there a way to display the produced images of the test?
