### ISSUE TITLE
failing test on documentation

### ISSUE THREAD

**Issue by rkanavath** [remicres/otb-mosaic#7]
Testing documentation for application Mosaic ...
Error in doc example: the list of parameter is empty.
https://dash.orfeo-toolbox.org/testDetails.php?test=60022403&build=287789

**Comment by remicres** [comment]
Should be fixed with [c6063d2c51aa845a6a89a4d3686d3c8a1ff09692](https://github.com/remicres/otb-mosaic/commit/c6063d2c51aa845a6a89a4d3686d3c8a1ff09692)

**Comment by rkanavath** [comment]
It is interesting to report bugs if it gets fixed in a fasttrack process..

Thanks remi, I guess the GIT_TAG is pointing to master. So it will be resolved on next day's dashboard.
